baseurl = "https://socialstory.netlify.com/"
title = "社交故事"
theme = "hugo-tracks-theme"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""


[params]
  # Use custom.css for your custom styling
  style = "default"
  pages = true
  description = "透過簡單完整的社交情景故事來教導兒童社交技巧及建立社交認知的。"
  copyright = "&copy;2018"
  email = "you@yoursite.com"

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = ""


  [params.social]
  email         = "hmlu36@gmail.com"
  github        = "https://github.com/hmlu36/SocialStory"
